----
title: "Radical Transparency in Organizational Structure"
date: 2019-06-11
----

author: Carl Olson


email: colson9@student.cscc.edu
description:

# social links
twitter_username: your-twitter-handle
github_username:  @Hunter71a

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
